version: '3.8'

services:
  quiz-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5276
      - ConnectionStrings__DefaultConnection=Server=Server=sqldata;Database=QuizBackendDatabase;user id=SA;password=Pass@word;Encrypt=false;TrustServerCertificate=true;Integrated Security=false;
    ports:
        - "5276:5276"

  sqldata:
      image: mcr.microsoft.com/mssql/server:2022-latest
      environment:
        - MSSQL_SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
      ports:
        - "1433:1433"
