name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Set up Docker build and push
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        image-name: mlab2024backend
        registry: mobitouchnet.azurecr.io 
        context: .
        push: true
        tags: mlab2024backend:${{ github.sha }}
